### ISSUE TITLE
gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.

### ISSUE THREAD

**Issue by phiphou** [shama/grunt-gulp#8]
This warning occurs and shoud'nt : "gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead."

**Comment by shama** [comment]
I don't use this plugin but happy to accept any PRs or give out commit access.

**Comment by metalbote** [comment]
#10

**Comment by ladytellur** [comment]
@shama hi, #10 resolves deprecation issue, could you please take a look?

**Comment by shama** [comment]
Thanks for the ping!
